[package]
name = "keystats-nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
luajit = ["mlua/luajit"]

[dependencies]
mlua = {version = "0.8.8", features = ["luajit", "vendored", "module", "serialize"]}
rusqlite = { version = "0.29.0", features = ["bundled"]}
